spring:
  profiles:
    active: qa

---
spring:
  profiles: dev

default:
  course:
    name: SAP HANA
    chapterCount: 3

course:
  name: AWS and DOCKER
  chapterCount: 45
  rating: 5
  author: kpilszak

---
spring:
  profiles: qa

default:
  course:
    name: SAP HANA QA
    chapterCount: 30

course:
  name: AWS or DOCKER
  chapterCount: 5
  rating: 6
  author: kpilszak
